### ISSUE TITLE
Environment Marker not shown 

### ISSUE THREAD

**Issue by magiva** [XjSv/environment-marker#249]
same as bug reported: 245
https://github.com/XjSv/environment-marker/issues/245

I have 3.0.1 and no change. no banner shows no matter what i do.
if i can help with logs, stats etc then just point me in the right direction and ill help where i can

**Comment by magiva** [comment]
permissions are set as you have shown.
script is running
![image](https://github.com/XjSv/environment-marker/assets/7522405/a98defc6-0aa6-4589-96d6-ae2d9daa7783)

i created a new environment marker for github and for wikipedia
![image](https://github.com/XjSv/environment-marker/assets/7522405/5dbaeec8-cc97-4cd4-8789-55054de42c79)

**Comment by magiva** [comment]
is there anything in inspector that would be useful.
i took a look but didnt see any activity

**Comment by magiva** [comment]
hmmm so interesting.....
i created a marker for wikipedia as suggested
i opened a new tab with control T and typed wikipedia and pressed enter
google opened with results and the marker was there.
i clicked on the wikipedia link, marker did not show
i went back to google result... marker did not show

**Comment by BlackMagicCoding** [comment]
i mean what you can try too is deactivating all extensions besides environment markers.
once i had a problem that the extension for keepass fucked up xml rendering for example.
just to make sure the issue is not related to something else.

can you show the marker for wikipedia? on your screenshot i only see github

**Comment by magiva** [comment]
![image](https://github.com/XjSv/environment-marker/assets/7522405/45de8a60-8c86-4781-8627-a97549c2c5db)

**Comment by magiva** [comment]
So repeatable method is google wikipedia, refresh the page,  click link.... no marker... refresh... marker shows

disabled all addons... marker shows as expected
re-enabled and repeated process of
load google, see marker, refresh google page, click wikipedia link... no marker / is marker
the refresh seemed important as i got inconsistent results first time of doing this.

the culprit is this
![image](https://github.com/XjSv/environment-marker/assets/7522405/cb95b5e9-25d9-44de-9d40-617896bff50d)

**Comment by magiva** [comment]
container tab definietly breaks it though :)

**Comment by XjSv** [comment]
First of all thanks to @BlackMagicCoding for taking the lead on this, your questions were very helpful. 

@magiva From reading the comments it seems to be some kind of loading or timing issue at first glance. 

At the core of this extension there is the background script that listens for `chrome.tabs.onUpdated`, so when a tab is updated and the status is `changeInfo.status === 'complete'` then the URL is checked and a marker applied if a match is found. 

From what you are explaining, I'm just wondering that when you click the link from Google, does the page finish loading? Because the weird part is that when you refresh the page the marker shows up.

**Comment by magiva** [comment]
yes as far as i can tell, everything completes.

if there is something in debugger i can monitor, let me know

**Comment by XjSv** [comment]
@magiva I can confirm that the issue happens when using containers as you described. When navigating back in history and then clicking the link again from the Google results it seems like there is something wrong.

**Comment by XjSv** [comment]
@magiva I'm struggling with reproducing the issue again. Initially I got it to reproduce once while playing around with going back and forth in history. I thought this was a MacOS only related bug because that's where I was able to trigger the issue. But after further tests I'm still struggling. Can you provide me with some additional information like what OS are you using, and what browser including the version?

OS: MacOS, Windows, Linux? What version?
Browser: Firefox, Chrome, Edge? Are you using the latest version?
Extension Settings:
1 - Is RegExp enabled in the settings?
2 - How are those 2 markers configured? I just need the URL fragment.

**Comment by XjSv** [comment]
Closing the issue due to inactivity. Feel free to open a new issue if the problem comes up again.
